<?php

namespace App\Domain\Content\Services;

/**
 * **El TEXTO de la política de cookies** (2.ª capa, `#219`), la de PRODUCCIÓN (`docs/specs/politica-de-cookies.md`; el
 * encargo del owner, 30-09: «con rigor y profesionalidad, con los datos del cliente»). FUENTE ÚNICA del sembrado
 * (`LandingContentSeeder::seedPages`); a una BD ya sembrada llega por `2026_09_30_150000_cookie_policy_for_production`, que
 * sustituye el texto anterior SOLO si sigue siendo exactamente el del producto (su huella) y no pisa lo editado.
 *
 * Estructura = la de `pages.body`: por idioma, una lista de secciones `{h, p}`. Los datos del responsable van como tokens
 * `:legal_name/:legal_nif/:legal_address/:legal_email`, que `LegalIdentity::interpolate()` sustituye EN EL RENDER por los
 * ajustes del panel: son los datos del cliente, y viven en su instalación.
 *
 * ⚠️⚠️ **El texto EXPLICA; el LISTADO de cookies no se escribe aquí.** Lo compone `CookieInventory` con lo que la instalación
 * tiene encendido (el mapa, el anti-bot, la herramienta de análisis, cada píxel) y lo pintan las vistas debajo de esto, así
 * que el texto habla de lo opcional en condicional («si esta web…») y remite al listado. Así no envejece: lo que decía
 * «recuérdame», el mapa CON las reseñas de Google o el widget de redes como si estuviera dejó de ser verdad sin que nadie
 * tocara esta clase (medido en el navegador el 30-09, `scripts/sonda-inventario-cookies.mjs`).
 *
 * El francés, de usted (el de la v4, de tú, sigue en `tests/Support/CookiePolicyV4.php` para las pruebas de las migraciones).
 */
class CookiePolicyContent
{
    /** @return array<string,string> */
    public static function title(): array
    {
        return ['es' => 'Política de cookies', 'en' => 'Cookie policy', 'fr' => 'Politique de cookies'];
    }

    /** @return array<string,array<int,array{h:string,p:string}>> */
    public static function body(): array
    {
        return [
            'es' => [
                ['h' => '¿Qué son las cookies?', 'p' => 'Las cookies son pequeños archivos que una web guarda en tu navegador para recordar algo de una página a otra o de una visita a la siguiente. Algunas son imprescindibles para que la web funcione; otras solo se instalan si tú lo autorizas.'],
                ['h' => '¿Quién es el responsable?', 'p' => 'El responsable es :legal_name, con NIF :legal_nif y domicilio en :legal_address. Para cualquier consulta sobre las cookies o sobre tus datos puedes escribir a :legal_email.'],
                ['h' => 'Qué cookies usamos', 'p' => 'Usamos cookies propias imprescindibles para prestarte el servicio, una cookie propia que mide la audiencia de forma anónima y, solo con tu permiso y cuando esa función está activa en esta web, cookies de terceros para el mapa, las redes sociales, el análisis de uso y la publicidad. Al final de esta política tienes el listado de las cookies de esta web, una a una: quién la pone, para qué, cuánto dura y cuándo. Lo compone la propia web con lo que tiene activo, así que siempre está al día.'],
                ['h' => 'Cookies necesarias (exentas de consentimiento)', 'p' => 'Sin ellas la web no puede prestarte el servicio que pides, y por eso no necesitan tu consentimiento (artículo 22.2 de la LSSI): mantienen tu visita y el recorrido de la compra, protegen los formularios frente a falsificaciones y guardan lo que decides en el aviso de cookies. Al pagar, te llevamos a la pasarela bancaria de Redsys, que usa sus propias cookies en su web para procesar el pago. Si esta web protege sus formularios con un sistema antibots, este puede instalar una cookie temporal de seguridad.'],
                ['h' => 'Mantener la sesión iniciada', 'p' => 'Cuando entras con el código que te enviamos al correo, puedes marcar «Mantener la sesión iniciada en este dispositivo». Solo entonces instalamos una cookie propia que te mantiene dentro durante 90 días desde tu última visita, o hasta que cierres sesión, para no pedirte un código cada vez. La casilla aparece sin marcar: esta cookie solo se pone si tú la pides. No la marques en un dispositivo que compartes con otras personas.'],
                ['h' => 'Medición de audiencia propia (exenta de consentimiento)', 'p' => 'Para saber cuántas personas visitan la web, qué páginas ven y desde qué campañas llegan, usamos una cookie propia, «visitor_id», que dura 13 meses y no se renueva en cada visita. Solo produce estadísticas anónimas para nosotros: no se cruza con otros sitios ni se cede a nadie, y los datos se conservan como máximo 25 meses. La Guía sobre el uso de las cookies de la AEPD exime de consentimiento esta medición, y por eso no te la pedimos; puedes borrar la cookie desde tu navegador cuando quieras.'],
                ['h' => 'Mapa (Google)', 'p' => 'Si esta web muestra un mapa de Google Maps para llegar, solo se carga cuando autorizas la categoría «Mapa (Google)». Al cargarlo, Google puede instalar sus propias cookies y recibir datos de tu navegador. Mientras no lo autorices, verás un aviso en su lugar y Google no instala nada.'],
                ['h' => 'Redes sociales', 'p' => 'Si esta web muestra nuestras publicaciones de redes sociales mediante un widget externo, solo se carga cuando autorizas la categoría «Redes sociales», y su proveedor puede instalar sus propias cookies. Mientras no lo autorices, no se instala ninguna.'],
                ['h' => 'Análisis de uso identificado', 'p' => 'Solo si lo autorizas en la categoría «Análisis de uso identificado», vinculamos tu navegación a tu cuenta cuando entras o compras, para entender cómo usas la web y mejorarla. Con ese mismo permiso, y si está activa, usamos también una herramienta de análisis de uso que recibe un identificador cifrado en lugar de tu nombre, sin tu dirección IP y con lo que escribes enmascarado. Si tienes cuenta, puedes retirar esta vinculación cuando quieras desde «Mi cuenta → Privacidad».'],
                ['h' => 'Publicidad', 'p' => 'Solo si lo autorizas en la categoría «Publicidad», y si hacemos campañas en ellas, cargamos los píxeles de las plataformas de anuncios (Google Ads, Meta o TikTok) y les comunicamos las compras que se completan, para saber qué anuncios funcionan. Reciben un identificador de la compra y tus datos de contacto solo transformados de forma irreversible (hash), nunca en claro, y pueden instalar sus propias cookies.'],
                ['h' => 'Transferencias internacionales de datos', 'p' => 'Algunas de las empresas de las cookies de terceros pueden tratar datos fuera del Espacio Económico Europeo. En el listado de abajo tienes, para cada una, la garantía que ampara esa transferencia (el marco EU-US Data Privacy Framework o las cláusulas contractuales tipo de la Comisión Europea).'],
                ['h' => '¿Cómo aceptar, configurar o retirar el consentimiento?', 'p' => 'La primera vez que visitas la web te mostramos un aviso para que puedas aceptar todas las cookies, rechazarlas o configurarlas por categoría. Puedes cambiar o retirar tu decisión en cualquier momento, con la misma facilidad con la que la diste, desde el enlace «Configuración de cookies» del pie de página. También puedes bloquear o borrar las cookies desde la configuración de tu navegador.'],
                ['h' => 'Cuánto guardamos tu decisión', 'p' => 'Guardamos tu decisión durante un máximo de 24 meses (algunos navegadores borran antes la cookie que la recuerda); pasado ese plazo te volveremos a preguntar. Te lo pediremos también antes si cambian las finalidades o los proveedores de las cookies que necesitan tu permiso.'],
                ['h' => 'Más información', 'p' => 'Para conocer en detalle cómo tratamos tus datos personales, consulta nuestra Política de privacidad.'],
            ],
            'en' => [
                ['h' => 'What are cookies?', 'p' => 'Cookies are small files that a website stores in your browser to remember something from one page to the next or from one visit to the next. Some are essential for the site to work; others are only installed if you allow them.'],
                ['h' => 'Who is responsible?', 'p' => 'The controller is :legal_name, tax ID :legal_nif, registered at :legal_address. For any question about cookies or about your data you can write to :legal_email.'],
                ['h' => 'Which cookies we use', 'p' => 'We use essential first-party cookies to provide the service, a first-party cookie that measures the audience anonymously and, only with your permission and when that feature is active on this site, third-party cookies for the map, social media, usage analytics and advertising. At the end of this policy you will find the list of this site\'s cookies, one by one: who sets it, what for, how long it lasts and when. The site builds it from what is active, so it is always up to date.'],
                ['h' => 'Necessary cookies (exempt from consent)', 'p' => 'Without them the site cannot provide the service you request, which is why they do not need your consent (Article 22.2 of the Spanish LSSI): they keep your visit and the purchase in progress, protect forms against forgery and store what you decide in the cookie notice. When you pay, we take you to the Redsys bank gateway, which uses its own cookies on its website to process the payment. If this site protects its forms with an anti-bot system, that system may install a temporary security cookie.'],
                ['h' => 'Keeping you signed in', 'p' => 'When you sign in with the code we email you, you can tick «Keep me signed in on this device». Only then do we install a first-party cookie that keeps you signed in for 90 days from your last visit, or until you sign out, so we do not ask you for a code every time. The box is unticked: this cookie is only set if you ask for it. Do not tick it on a device you share with other people.'],
                ['h' => 'Our own audience measurement (exempt from consent)', 'p' => 'To know how many people visit the site, which pages they see and which campaigns bring them, we use a first-party cookie, «visitor_id», which lasts 13 months and is not renewed on each visit. It only produces anonymous statistics for us: it is not cross-referenced with other sites nor shared with anyone, and the data is kept for at most 25 months. The Spanish Data Protection Agency\'s (AEPD) guide on the use of cookies exempts this measurement from consent, which is why we do not ask for it; you can delete the cookie from your browser whenever you want.'],
                ['h' => 'Map (Google)', 'p' => 'If this site shows a Google Maps map to get here, it only loads when you allow the «Map (Google)» category. When it loads, Google may install its own cookies and receive data from your browser. Until you allow it, you will see a notice in its place and Google installs nothing.'],
                ['h' => 'Social media', 'p' => 'If this site shows our social media posts through an external widget, it only loads when you allow the «Social media» category, and its provider may install its own cookies. Until you allow it, none are installed.'],
                ['h' => 'Identified usage analytics', 'p' => 'Only if you allow it under the «Identified usage analytics» category, we link your browsing to your account when you sign in or buy, to understand how you use the site and improve it. With that same permission, and if it is active, we also use a usage analytics tool that receives an encrypted identifier instead of your name, without your IP address and with what you type masked. If you have an account, you can withdraw this link at any time from «My account → Privacy».'],
                ['h' => 'Advertising', 'p' => 'Only if you allow it under the «Advertising» category, and if we run campaigns on them, we load the pixels of the advertising platforms (Google Ads, Meta or TikTok) and report completed purchases to them, to know which ads work. They receive a purchase identifier and your contact details only transformed irreversibly (hashed), never in the clear, and they may install their own cookies.'],
                ['h' => 'International data transfers', 'p' => 'Some of the companies behind third-party cookies may process data outside the European Economic Area. In the list below you will find, for each one, the safeguard covering that transfer (the EU-US Data Privacy Framework or the European Commission\'s standard contractual clauses).'],
                ['h' => 'How to accept, configure or withdraw consent', 'p' => 'The first time you visit the site we show a notice so you can accept all cookies, reject them or configure them by category. You can change or withdraw your decision at any time, as easily as you gave it, from the «Cookie settings» link in the footer. You can also block or delete cookies from your browser settings.'],
                ['h' => 'How long we keep your decision', 'p' => 'We keep your decision for a maximum of 24 months (some browsers delete the cookie that remembers it sooner); after that we will ask you again. We will also ask sooner if the purposes or the providers of the cookies that need your permission change.'],
                ['h' => 'More information', 'p' => 'To learn in detail how we handle your personal data, see our Privacy policy.'],
            ],
            'fr' => [
                ['h' => 'Que sont les cookies ?', 'p' => 'Les cookies sont de petits fichiers qu\'un site enregistre dans votre navigateur pour se souvenir de quelque chose d\'une page à l\'autre ou d\'une visite à la suivante. Certains sont indispensables au fonctionnement du site ; d\'autres ne sont installés que si vous les autorisez.'],
                ['h' => 'Qui est le responsable ?', 'p' => 'Le responsable est :legal_name, NIF :legal_nif, domicilié à :legal_address. Pour toute question sur les cookies ou sur vos données, vous pouvez écrire à :legal_email.'],
                ['h' => 'Les cookies que nous utilisons', 'p' => 'Nous utilisons des cookies propres indispensables pour vous fournir le service, un cookie propre qui mesure l\'audience de façon anonyme et, uniquement avec votre accord et lorsque cette fonction est active sur ce site, des cookies de tiers pour la carte, les réseaux sociaux, l\'analyse d\'usage et la publicité. À la fin de cette politique, vous trouverez la liste des cookies de ce site, un par un : qui le dépose, à quoi il sert, combien de temps il dure et quand. Le site l\'établit lui-même à partir de ce qui est actif : elle est donc toujours à jour.'],
                ['h' => 'Cookies nécessaires (exemptés de consentement)', 'p' => 'Sans eux, le site ne peut pas vous fournir le service que vous demandez ; c\'est pourquoi ils ne nécessitent pas votre consentement (article 22.2 de la LSSI espagnole) : ils maintiennent votre visite et l\'achat en cours, protègent les formulaires contre la falsification et conservent ce que vous décidez dans l\'avis sur les cookies. Au moment de payer, nous vous dirigeons vers la passerelle bancaire de Redsys, qui utilise ses propres cookies sur son site pour traiter le paiement. Si ce site protège ses formulaires avec un système anti-robots, celui-ci peut déposer un cookie de sécurité temporaire.'],
                ['h' => 'Rester connecté', 'p' => 'Lorsque vous vous connectez avec le code que nous vous envoyons par e-mail, vous pouvez cocher « Rester connecté sur cet appareil ». Ce n\'est qu\'alors que nous déposons un cookie propre qui vous garde connecté pendant 90 jours depuis votre dernière visite, ou jusqu\'à votre déconnexion, pour ne pas vous demander un code à chaque fois. La case n\'est pas cochée : ce cookie n\'est déposé que si vous le demandez. Ne la cochez pas sur un appareil que vous partagez avec d\'autres personnes.'],
                ['h' => 'Mesure d\'audience propre (exemptée de consentement)', 'p' => 'Pour savoir combien de personnes visitent le site, quelles pages elles consultent et de quelles campagnes elles viennent, nous utilisons un cookie propre, « visitor_id », qui dure 13 mois et n\'est pas renouvelé à chaque visite. Il ne produit que des statistiques anonymes pour nous : il n\'est ni croisé avec d\'autres sites ni cédé à qui que ce soit, et les données sont conservées 25 mois au maximum. Le guide sur l\'utilisation des cookies de l\'autorité espagnole de protection des données (AEPD) exempte cette mesure de consentement ; c\'est pourquoi nous ne vous le demandons pas. Vous pouvez supprimer le cookie depuis votre navigateur quand vous le souhaitez.'],
                ['h' => 'Carte (Google)', 'p' => 'Si ce site affiche une carte Google Maps pour venir, elle ne se charge que lorsque vous autorisez la catégorie « Carte (Google) ». Lors de son chargement, Google peut déposer ses propres cookies et recevoir des données de votre navigateur. Tant que vous ne l\'autorisez pas, vous verrez un message à sa place et Google ne dépose rien.'],
                ['h' => 'Réseaux sociaux', 'p' => 'Si ce site affiche nos publications sur les réseaux sociaux au moyen d\'un widget externe, celui-ci ne se charge que lorsque vous autorisez la catégorie « Réseaux sociaux », et son prestataire peut déposer ses propres cookies. Tant que vous ne l\'autorisez pas, aucun n\'est déposé.'],
                ['h' => 'Analyse d\'usage identifiée', 'p' => 'Seulement si vous l\'autorisez dans la catégorie « Analyse d\'usage identifiée », nous lions votre navigation à votre compte lorsque vous vous connectez ou achetez, pour comprendre comment vous utilisez le site et l\'améliorer. Avec cette même autorisation, et s\'il est actif, nous utilisons aussi un outil d\'analyse d\'usage qui reçoit un identifiant chiffré à la place de votre nom, sans votre adresse IP et avec ce que vous saisissez masqué. Si vous avez un compte, vous pouvez retirer ce lien à tout moment depuis « Mon compte → Confidentialité ».'],
                ['h' => 'Publicité', 'p' => 'Seulement si vous l\'autorisez dans la catégorie « Publicité », et si nous y menons des campagnes, nous chargeons les pixels des plateformes publicitaires (Google Ads, Meta ou TikTok) et leur communiquons les achats finalisés, pour savoir quelles annonces fonctionnent. Elles reçoivent un identifiant de l\'achat et vos coordonnées uniquement transformées de façon irréversible (hachage), jamais en clair, et peuvent déposer leurs propres cookies.'],
                ['h' => 'Transferts internationaux de données', 'p' => 'Certaines des sociétés à l\'origine des cookies de tiers peuvent traiter des données hors de l\'Espace économique européen. Dans la liste ci-dessous, vous trouverez pour chacune la garantie qui encadre ce transfert (le cadre EU-US Data Privacy Framework ou les clauses contractuelles types de la Commission européenne).'],
                ['h' => 'Comment accepter, configurer ou retirer votre consentement', 'p' => 'Lors de votre première visite, nous affichons un avis pour que vous puissiez accepter tous les cookies, les refuser ou les configurer par catégorie. Vous pouvez modifier ou retirer votre décision à tout moment, aussi facilement que vous l\'avez donnée, depuis le lien « Configuration des cookies » en pied de page. Vous pouvez aussi bloquer ou supprimer les cookies depuis les réglages de votre navigateur.'],
                ['h' => 'Combien de temps nous conservons votre décision', 'p' => 'Nous conservons votre décision pendant 24 mois au maximum (certains navigateurs suppriment plus tôt le cookie qui la mémorise) ; passé ce délai, nous vous la redemanderons. Nous vous la redemanderons aussi plus tôt si les finalités ou les fournisseurs des cookies soumis à votre accord changent.'],
                ['h' => 'Plus d\'informations', 'p' => 'Pour savoir en détail comment nous traitons vos données personnelles, consultez notre Politique de confidentialité.'],
            ],
        ];
    }
}
