@props(['src' => null, 'poster' => null, 'kind' => 'video', 'aspect' => 'var(--ar-wide)', 'caption' => '', 'alt' => '', 'badge' => null, 'rounded' => 'var(--r-xl)', 'focus' => '50% 50%', 'note' => '', 'flat' => false, 'fill' => false])
@php
    /*
     * El marco de vídeo o imagen (`content/MediaFrame.jsx`), con sus estilos EN LÍNEA como el JSX. Sin `src` enseña el
     * hueco marcado con su nota. El vídeo que arranca al entrar en pantalla es JS de la página (`data-marco-video`);
     * con movimiento reducido, controles y quieto.
     */
    $estilo = 'display: flex; flex-direction: column; gap: var(--space-3); margin: 0;'.($fill ? ' height: 100%; min-height: 0;' : '');
    if ($attributes->has('style')) {
        $estilo .= ' '.$attributes->get('style');
    }
    $caja = 'position: relative; aspect-ratio: '.$aspect.'; overflow: hidden; border-radius: '.$rounded.'; background: var(--fiesta-tinta-800); box-shadow: '.($flat ? 'none' : 'var(--shadow-md)').';'.($fill ? ' flex: 1 1 auto; min-height: 0;' : '');
@endphp
<figure style="{{ $estilo }}" {{ $attributes->except('style') }}><div style="{{ $caja }}">@if ($src && $kind === 'video')<video src="{{ $src }}" @if ($poster) poster="{{ $poster }}" @endif muted loop playsinline preload="metadata" data-marco-video style="width: 100%; height: 100%; object-fit: cover; object-position: {{ $focus }};"></video>@elseif ($src)<img src="{{ $src }}" alt="{{ $alt !== '' ? $alt : $caption }}" loading="lazy" decoding="async" style="width: 100%; height: 100%; object-fit: cover; object-position: {{ $focus }};">@else<div style="position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 10px; background: repeating-linear-gradient(135deg, rgba(255,255,255,0.05) 0 12px, rgba(255,255,255,0) 12px 24px), var(--fiesta-tinta-800); color: rgba(255,255,255,0.5);"><span style="display: inline-flex; align-items: center; justify-content: center; width: 54px; height: 54px; border-radius: 50%; border: 1px dashed rgba(255,255,255,0.32); color: rgba(255,255,255,0.6);"><x-lucide :name="$kind === 'image' ? 'camera' : 'play'" :size="22" /></span><span style="max-width: 78%; text-align: center; font-family: var(--font-mono); font-size: var(--fs-caption); line-height: 1.45;">{{ $note !== '' ? $note : ($kind === 'image' ? __('fiesta.pieza.hueco_foto') : __('fiesta.pieza.hueco_video')) }}</span></div>@endif{{ '' }}@if ($badge)<span style="position: absolute; left: 12px; top: 12px; display: inline-flex; align-items: center; gap: 7px; height: 28px; padding: 0 12px; border-radius: var(--r-pill); background: rgba(9,46,74,0.66); -webkit-backdrop-filter: var(--blur-veil); backdrop-filter: var(--blur-veil); color: var(--fiesta-nieve); font-family: var(--font-ui); font-size: var(--fs-overline); font-weight: var(--fw-bold); letter-spacing: 0.06em;">{{ $badge }}</span>@endif</div>@if ($caption !== '')<figcaption style="font-family: var(--font-ui); font-size: var(--fs-caption); color: var(--text-muted);">{{ $caption }}</figcaption>@endif</figure>