<?php

namespace App\Support;

/**
 * Contenido real de las páginas legales editables (#220): Política de privacidad, Términos y
 * condiciones y Aviso legal. FUENTE ÚNICA usada por el seeder (instalación limpia) y por la
 * migración de reparación idempotente (reemplaza el contenido `[PENDIENTE]` heredado solo si
 * persiste — no pisa ediciones de la clienta). Espejo de [[CookiePolicyContent]].
 *
 * Redactado de forma EMPÍRICA (anclado al código: datos tratados, flujos, bases jurídicas,
 * terceros, conservación, seguridad y derechos). Los datos fiscales del responsable van como
 * tokens `:legal_name/:legal_nif/:legal_address/:legal_email`, que `LegalIdentity::interpolate()`
 * sustituye EN EL RENDER por los settings de `/admin/settings`. Los datos de negocio NO decididos
 * quedan como `[PENDIENTE: …]` (plazos de cancelación, fuero, etc.) para que los aporte la clienta.
 *
 * ⚠️ Texto técnico-orientativo que refleja el tratamiento REAL del sistema; la redacción legal
 * definitiva la valida la asesoría jurídica de la clienta.
 */
class LegalContent
{
    /**
     * @return array<string,array{title:array<string,string>,body:array<string,array<int,array{h:string,p:string}>>}>
     */
    public static function pages(): array
    {
        return [
            'privacidad' => [
                'title' => ['es' => 'Política de privacidad', 'en' => 'Privacy policy', 'fr' => 'Politique de confidentialité'],
                'body' => [
                    'es' => [
                        ['h' => 'Responsable del tratamiento', 'p' => 'El responsable del tratamiento de tus datos es :legal_name, con NIF :legal_nif y domicilio en :legal_address. Para cualquier cuestión relativa a esta política o al ejercicio de tus derechos puedes escribirnos a :legal_email.'],
                        ['h' => 'Qué datos tratamos y cómo los obtenemos', 'p' => 'Tratamos los datos que tú nos facilitas y los que se generan al usar la web. Al registrarte y crear tu cuenta recogemos tu nombre, tu correo electrónico, tu teléfono, tu contraseña (que guardamos siempre cifrada, nunca en claro) y tu idioma preferido. Al comprar entradas o reservar un pack tratamos los datos de tu pedido: productos, franja horaria, cantidades, importes y estado del pago. En las reservas de cumpleaños y eventos tratamos además la información que indiques en el formulario de reserva (por ejemplo notas u observaciones) y, en su caso, los datos que el formulario solicite por cada invitado. Al navegar generamos datos técnicos y de seguridad: tu dirección IP, el tipo de navegador y registros de actividad (logs) para mantener tu sesión, prevenir el abuso y proteger la cuenta. También usamos cookies; el detalle está en nuestra Política de cookies, a la que puedes acceder desde el pie de página.'],
                        ['h' => 'Datos de menores y datos de salud (reservas de cumpleaños)', 'p' => 'Cuando contratas un cumpleaños te pedimos cumplimentar un formulario por cada niño o niña invitada, que puede incluir su nombre, alergias o intolerancias, observaciones y menú especial. Esta información incluye datos de menores y datos de salud (las alergias e intolerancias son una categoría especial de datos). Solo los tratamos para organizar el evento que has contratado y garantizar la seguridad alimentaria. El tratamiento de los datos de salud (alergias e intolerancias), por ser una categoría especial, se ampara en el consentimiento explícito del adulto responsable parental (art. 9.2.a RGPD) y, cuando proceda, en la protección de un interés vital del menor para la seguridad alimentaria (art. 9.2.c RGPD). Debe ser siempre el adulto que contrata el cumpleaños, en su condición de responsable parental o de quien ostente la patria potestad o tutela de los menores, quien aporte estos datos con su consentimiento; al introducirlos en el formulario nos confirmas que cuentas con dicha autorización. El conjunto exacto de campos que se solicita en el formulario de reserva o por invitado puede variar, ya que es configurable; en todo caso solo pedimos lo necesario para prestar el servicio contratado.'],
                        ['h' => 'Para qué usamos tus datos y con qué base jurídica', 'p' => 'Tratamos tus datos para crear y gestionar tu cuenta, tramitar tus compras y reservas, emitir las entradas, controlar el acceso al parque y atender tus consultas; la base jurídica es la ejecución del contrato de compra o las medidas precontractuales que solicitas (art. 6.1.b RGPD). Para enviarte comunicaciones comerciales, novedades u ofertas tratamos tus datos únicamente si nos das tu consentimiento, que es libre y revocable (art. 6.1.a RGPD); también es el consentimiento la base para cargar las cookies no necesarias. Para emitir y conservar las facturas y la documentación contable tratamos tus datos por obligación legal (art. 6.1.c RGPD). Y para garantizar la seguridad de la web y de tu cuenta, prevenir el fraude y poder acreditar los consentimientos prestados nos basamos en nuestro interés legítimo y en el deber de responsabilidad proactiva (arts. 6.1.f, 5.2 y 32 RGPD).'],
                        ['h' => 'Destinatarios y encargados del tratamiento', 'p' => 'No vendemos tus datos. Para prestarte el servicio recurrimos a proveedores que tratan datos por cuenta nuestra, como encargados del tratamiento: la entidad de pago Redsys y la entidad bancaria, que procesan el cobro con tarjeta; Cloudflare, cuyo sistema antibot (Turnstile) protege nuestros formularios cuando está activado; nuestro proveedor de envío de correo electrónico (verificaciones, avisos de pedido y similares); y nuestro proveedor de alojamiento (hosting), que aloja la aplicación y la base de datos. También utilizamos Bunny Fonts (BunnyWay d.o.o., con sede en Eslovenia, UE) para servir las tipografías del sitio; este proveedor recibe la dirección IP de tu navegador en cada carga, no usa cookies y se ofrece como conforme al RGPD, por lo que no implica una transferencia internacional fuera de la UE. El pago se realiza siempre dentro del entorno seguro de Redsys: no almacenamos los datos de tu tarjeta. De la respuesta del pago solo conservamos la información necesaria para el soporte y la conciliación (marca y país de la tarjeta, códigos de autorización, importes y fechas), nunca el número de tu tarjeta. La identidad del proveedor de correo y la del proveedor de alojamiento están [PENDIENTE: designar proveedor de correo y de alojamiento].'],
                        ['h' => 'Contenidos de terceros (mapa y redes sociales)', 'p' => 'Si lo has consentido a través del aviso de cookies, mostramos contenidos incrustados de terceros: el mapa de Google Maps (Google) y, en la galería, el muro de Instagram o TikTok a través de servicios como SnapWidget o LightWidget. Mientras no los aceptes, estos contenidos no se cargan. Estos proveedores pueden recibir tu dirección IP y datos de tu navegador. Tienes el detalle en la Política de cookies.'],
                        ['h' => 'Transferencias internacionales de datos', 'p' => 'Algunos de los proveedores anteriores son empresas con sede en Estados Unidos: Cloudflare (antibot), Google (mapa) y los servicios del muro social (SnapWidget/LightWidget). Si están activos, el uso de estos servicios implica una transferencia internacional de datos a Estados Unidos, amparada habitualmente en el marco de privacidad de datos UE-EE. UU. (Data Privacy Framework) o en cláusulas contractuales tipo. El mecanismo de transferencia concreto de cada proveedor está [PENDIENTE: confirmar Data Privacy Framework o cláusulas tipo de cada proveedor]. La ubicación de los servidores de nuestro proveedor de alojamiento y, por tanto, si existe transferencia internacional por el hosting, está [PENDIENTE: confirmar ubicación del servidor de alojamiento].'],
                        ['h' => 'Durante cuánto tiempo conservamos tus datos', 'p' => 'Conservamos los datos de tu cuenta mientras la mantengas activa y, después, durante los plazos legales que nos obliguen; en concreto, los datos asociados a tus pedidos y facturas se conservan durante los plazos exigidos por la normativa fiscal y mercantil. El plazo fiscal concreto de conservación de la documentación contable está [PENDIENTE: confirmar plazo de conservación fiscal con el gestor (orientativo, entre 4 y 6 años)]. Los pedidos que dejas pendientes de pago caducan automáticamente al expirar la reserva de plaza, liberando el aforo. Los registros que acreditan tu consentimiento de cookies se conservan un máximo de 24 meses. Tu sesión caduca tras un periodo de inactividad.'],
                        ['h' => 'Tus derechos', 'p' => 'Puedes ejercer en cualquier momento los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad, así como retirar los consentimientos que hayas prestado, sin que ello afecte a la licitud del tratamiento previo. Para tu comodidad, varios de estos derechos los puedes ejercer tú mismo desde «Mi cuenta»: descargar una copia de todos tus datos en un fichero legible por máquina (acceso y portabilidad) desde la opción de exportar, y rectificar tu nombre, teléfono, idioma o correo electrónico directamente en tu perfil. Para suprimir tu cuenta puedes hacerlo también desde «Mi cuenta»: en lugar de borrar tus pedidos, anonimizamos tu cuenta (sobrescribimos tu nombre, correo, teléfono y contraseña, y eliminamos tus consentimientos), conservando únicamente lo imprescindible para cumplir nuestras obligaciones fiscales sobre las facturas. Para ejercer el resto de derechos, como la oposición o la limitación, o si prefieres solicitarnos el acceso o la supresión por escrito, escríbenos a :legal_email; podremos pedirte que acredites tu identidad.'],
                        ['h' => 'Comunicaciones comerciales y cómo darte de baja', 'p' => 'Solo te enviaremos comunicaciones comerciales si lo has consentido expresamente al registrarte, y nunca de forma premarcada. Puedes retirar este consentimiento en cualquier momento escribiéndonos a :legal_email. El mecanismo de baja directa desde la propia comunicación o desde tu cuenta está [PENDIENTE: confirmar mecanismo de baja de marketing].'],
                        ['h' => 'Decisiones automatizadas y elaboración de perfiles', 'p' => 'No tomamos decisiones automatizadas que produzcan efectos jurídicos sobre ti o te afecten significativamente, ni elaboramos perfiles con tus datos.'],
                        ['h' => 'Medidas de seguridad', 'p' => 'Aplicamos medidas técnicas y organizativas para proteger tus datos. Tu contraseña se guarda siempre cifrada y comprobamos que no figure en filtraciones de datos conocidas antes de aceptarla. Verificamos tu correo mediante un enlace que caduca y, si cambias de email, no sustituimos el actual hasta que confirmas el nuevo, avisando al anterior. Limitamos los intentos de inicio de sesión y registro para frenar ataques de fuerza bruta, y protegemos los formularios públicos frente a bots. Las sesiones se gestionan con cookies seguras y puedes cerrarlas en otros dispositivos. Aplicamos cabeceras de seguridad y una política de seguridad de contenido (CSP) en la web. En nuestros registros internos minimizamos los datos: no guardamos contraseñas ni identificadores sensibles en claro, sino cifrados o anonimizados.'],
                        ['h' => 'Reclamación ante la autoridad de control', 'p' => 'Si consideras que el tratamiento de tus datos no se ajusta a la normativa, tienes derecho a presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD), con domicilio en C/ Jorge Juan, 6, 28001 Madrid, y a través de su sede electrónica en www.aepd.es. No obstante, te agradeceríamos que, antes, te pusieras en contacto con nosotros en :legal_email para intentar resolver tu solicitud.'],
                    ],
                    'en' => [
                        ['h' => 'Data controller', 'p' => 'The controller of your data is :legal_name, tax ID :legal_nif, registered at :legal_address. For any matter relating to this policy or to exercising your rights you can write to us at :legal_email.'],
                        ['h' => 'What data we process and how we collect it', 'p' => 'We process the data you provide and the data generated when you use the website. When you register and create an account we collect your name, email address, phone number, your password (which we always store encrypted, never in plain text) and your preferred language. When you buy tickets or book a pack we process your order data: products, time slot, quantities, amounts and payment status. For birthday and event bookings we also process the information you enter in the booking form (for example notes or remarks) and, where applicable, the data the form requests for each guest. While you browse we generate technical and security data: your IP address, browser type and activity logs, used to keep your session, prevent abuse and protect your account. We also use cookies; the details are in our Cookie policy, which you can access from the footer.'],
                        ['h' => 'Minors\' data and health data (birthday bookings)', 'p' => 'When you book a birthday party we ask you to complete a form for each invited child, which may include their name, allergies or intolerances, remarks and special menu. This information includes minors\' data and health data (allergies and intolerances are a special category of data). We only process it to organise the event you have booked and to ensure food safety. The processing of health data (allergies and intolerances), being a special category, is based on the explicit consent of the responsible parent adult (Art. 9.2.a GDPR) and, where applicable, on the protection of the child\'s vital interest for food safety (Art. 9.2.c GDPR). The data must always be provided by the adult booking the party, acting as the parent, guardian or person holding parental authority over the children, with their consent; by entering it in the form you confirm that you have such authorisation. The exact set of fields requested in the booking form or per guest may vary, as it is configurable; in any case we only ask for what is necessary to provide the service you have booked.'],
                        ['h' => 'Why we use your data and on what legal basis', 'p' => 'We process your data to create and manage your account, handle your purchases and bookings, issue tickets, control park access and respond to your enquiries; the legal basis is the performance of the purchase contract or the pre-contractual steps you request (Art. 6.1.b GDPR). We process your data to send you marketing, news or offers only if you give us your consent, which is freely given and revocable (Art. 6.1.a GDPR); consent is also the basis for loading non-essential cookies. We process your data to issue and keep invoices and accounting records under a legal obligation (Art. 6.1.c GDPR). And to keep the website and your account secure, prevent fraud and be able to evidence the consents given, we rely on our legitimate interest and the duty of accountability (Arts. 6.1.f, 5.2 and 32 GDPR).'],
                        ['h' => 'Recipients and data processors', 'p' => 'We do not sell your data. To provide the service we use suppliers that process data on our behalf, as data processors: the payment provider Redsys and the bank, which process the card payment; Cloudflare, whose anti-bot system (Turnstile) protects our forms when enabled; our email delivery provider (verifications, order notices and similar); and our hosting provider, which hosts the application and the database. We also use Bunny Fonts (BunnyWay d.o.o., based in Slovenia, EU) to serve the website fonts; this provider receives your browser\'s IP address on each load, uses no cookies and is offered as GDPR-compliant, so it does not involve an international transfer outside the EU. Payment always takes place within the secure Redsys environment: we do not store your card details. From the payment response we keep only the information needed for support and reconciliation (card brand and country, authorisation codes, amounts and dates), never your card number. The identity of the email provider and the hosting provider is [PENDING: designate email and hosting provider].'],
                        ['h' => 'Third-party content (map and social media)', 'p' => 'If you have consented through the cookie banner, we display embedded third-party content: the Google Maps map (Google) and, in the gallery, the Instagram or TikTok feed through services such as SnapWidget or LightWidget. Until you accept them, this content is not loaded. These providers may receive your IP address and browser data. You will find the details in the Cookie policy.'],
                        ['h' => 'International data transfers', 'p' => 'Some of the above providers are companies based in the United States: Cloudflare (anti-bot), Google (map) and the social feed services (SnapWidget/LightWidget). When active, using these services involves an international data transfer to the United States, usually covered by the EU-US Data Privacy Framework or by standard contractual clauses. The specific transfer mechanism of each provider is [PENDING: confirm Data Privacy Framework or standard clauses for each provider]. The location of our hosting provider\'s servers, and therefore whether there is an international transfer through hosting, is [PENDING: confirm hosting server location].'],
                        ['h' => 'How long we keep your data', 'p' => 'We keep your account data while your account remains active and, afterwards, for the legal periods we are required to; in particular, data linked to your orders and invoices is kept for the periods required by tax and commercial law. The specific tax retention period for accounting records is [PENDING: confirm tax retention period with the accountant (typically 4 to 6 years)]. Orders you leave unpaid expire automatically when the seat hold lapses, releasing the capacity. The records evidencing your cookie consent are kept for a maximum of 24 months. Your session expires after a period of inactivity.'],
                        ['h' => 'Your rights', 'p' => 'You may exercise at any time your rights of access, rectification, erasure, objection, restriction of processing and portability, and withdraw any consent you have given, without affecting the lawfulness of prior processing. For your convenience, several of these rights you can exercise yourself from "My account": download a copy of all your data in a machine-readable file (access and portability) from the export option, and rectify your name, phone, language or email directly in your profile. You can also delete your account from "My account": instead of deleting your orders, we anonymise your account (we overwrite your name, email, phone and password, and remove your consents), keeping only what is strictly necessary to comply with our tax obligations regarding invoices. To exercise the remaining rights, such as objection or restriction, or if you prefer to request access or erasure in writing, write to us at :legal_email; we may ask you to prove your identity.'],
                        ['h' => 'Marketing communications and how to unsubscribe', 'p' => 'We will only send you marketing communications if you have expressly consented when registering, never pre-ticked. You can withdraw this consent at any time by writing to us at :legal_email. The mechanism to unsubscribe directly from the communication itself or from your account is [PENDING: confirm marketing unsubscribe mechanism].'],
                        ['h' => 'Automated decisions and profiling', 'p' => 'We do not make automated decisions producing legal effects on you or significantly affecting you, nor do we carry out profiling with your data.'],
                        ['h' => 'Security measures', 'p' => 'We apply technical and organisational measures to protect your data. Your password is always stored encrypted, and we check that it does not appear in known data breaches before accepting it. We verify your email through an expiring link and, if you change your email, we do not replace the current one until you confirm the new one, notifying the old one. We limit login and registration attempts to deter brute-force attacks, and we protect public forms against bots. Sessions are managed with secure cookies and you can close them on other devices. We apply security headers and a content security policy (CSP) on the website. In our internal logs we minimise data: we do not store passwords or sensitive identifiers in plain text, but encrypted or anonymised.'],
                        ['h' => 'Complaint to the supervisory authority', 'p' => 'If you believe that the processing of your data does not comply with the regulations, you have the right to lodge a complaint with the Spanish Data Protection Agency (AEPD), located at C/ Jorge Juan, 6, 28001 Madrid, and through its electronic office at www.aepd.es. However, we would appreciate it if you first contacted us at :legal_email to try to resolve your request.'],
                    ],
                    'fr' => [
                        ['h' => 'Responsable du traitement', 'p' => 'Le responsable du traitement de tes données est :legal_name, NIF :legal_nif, domicilié à :legal_address. Pour toute question relative à cette politique ou à l\'exercice de tes droits, tu peux nous écrire à :legal_email.'],
                        ['h' => 'Quelles données nous traitons et comment nous les obtenons', 'p' => 'Nous traitons les données que tu nous fournis et celles générées lors de l\'utilisation du site. Lors de ton inscription et de la création de ton compte, nous recueillons ton nom, ton adresse email, ton téléphone, ton mot de passe (que nous conservons toujours chiffré, jamais en clair) et ta langue préférée. Lors de l\'achat de billets ou de la réservation d\'un pack, nous traitons les données de ta commande : produits, créneau horaire, quantités, montants et statut du paiement. Pour les réservations d\'anniversaires et d\'événements, nous traitons aussi les informations que tu saisis dans le formulaire de réservation (par exemple des notes ou remarques) et, le cas échéant, les données demandées pour chaque invité. Pendant ta navigation, nous générons des données techniques et de sécurité : ton adresse IP, le type de navigateur et des journaux d\'activité, utilisés pour maintenir ta session, prévenir les abus et protéger ton compte. Nous utilisons également des cookies ; le détail figure dans notre Politique de cookies, accessible depuis le pied de page.'],
                        ['h' => 'Données de mineurs et données de santé (réservations d\'anniversaire)', 'p' => 'Lorsque tu réserves un anniversaire, nous te demandons de remplir un formulaire pour chaque enfant invité, qui peut inclure son nom, ses allergies ou intolérances, des remarques et un menu spécial. Ces informations comprennent des données de mineurs et des données de santé (les allergies et intolérances sont une catégorie particulière de données). Nous ne les traitons que pour organiser l\'événement que tu as réservé et garantir la sécurité alimentaire. Le traitement des données de santé (allergies et intolérances), en tant que catégorie particulière, repose sur le consentement explicite de l\'adulte responsable parental (art. 9.2.a RGPD) et, le cas échéant, sur la protection d\'un intérêt vital de l\'enfant pour la sécurité alimentaire (art. 9.2.c RGPD). Ces données doivent toujours être fournies par l\'adulte qui réserve l\'anniversaire, en tant que parent, tuteur ou titulaire de l\'autorité parentale sur les enfants, avec son consentement ; en les saisissant dans le formulaire, tu confirmes disposer de cette autorisation. L\'ensemble exact des champs demandés dans le formulaire de réservation ou par invité peut varier, car il est configurable ; dans tous les cas, nous ne demandons que ce qui est nécessaire pour fournir le service réservé.'],
                        ['h' => 'Pourquoi nous utilisons tes données et sur quelle base juridique', 'p' => 'Nous traitons tes données pour créer et gérer ton compte, traiter tes achats et réservations, émettre les billets, contrôler l\'accès au parc et répondre à tes demandes ; la base juridique est l\'exécution du contrat d\'achat ou les mesures précontractuelles que tu sollicites (art. 6.1.b RGPD). Nous traitons tes données pour t\'envoyer des communications commerciales, nouveautés ou offres uniquement si tu nous donnes ton consentement, libre et révocable (art. 6.1.a RGPD) ; le consentement est aussi la base du dépôt des cookies non nécessaires. Nous traitons tes données pour émettre et conserver les factures et la comptabilité au titre d\'une obligation légale (art. 6.1.c RGPD). Et pour garantir la sécurité du site et de ton compte, prévenir la fraude et pouvoir prouver les consentements donnés, nous nous fondons sur notre intérêt légitime et sur le devoir de responsabilité (art. 6.1.f, 5.2 et 32 RGPD).'],
                        ['h' => 'Destinataires et sous-traitants', 'p' => 'Nous ne vendons pas tes données. Pour te fournir le service, nous recourons à des prestataires qui traitent des données pour notre compte, en tant que sous-traitants : le prestataire de paiement Redsys et la banque, qui traitent le paiement par carte ; Cloudflare, dont le système anti-bot (Turnstile) protège nos formulaires lorsqu\'il est activé ; notre prestataire d\'envoi d\'emails (vérifications, avis de commande, etc.) ; et notre hébergeur, qui héberge l\'application et la base de données. Nous utilisons aussi Bunny Fonts (BunnyWay d.o.o., établie en Slovénie, UE) pour servir les polices du site ; ce prestataire reçoit l\'adresse IP de ton navigateur à chaque chargement, n\'utilise pas de cookies et se présente comme conforme au RGPD, il n\'implique donc pas de transfert international hors UE. Le paiement a toujours lieu dans l\'environnement sécurisé de Redsys : nous ne stockons pas les données de ta carte. De la réponse de paiement, nous ne conservons que les informations nécessaires au support et au rapprochement (marque et pays de la carte, codes d\'autorisation, montants et dates), jamais le numéro de ta carte. L\'identité du prestataire d\'emails et celle de l\'hébergeur sont [À COMPLÉTER : désigner le prestataire d\'emails et l\'hébergeur].'],
                        ['h' => 'Contenus de tiers (carte et réseaux sociaux)', 'p' => 'Si tu y as consenti via le bandeau cookies, nous affichons des contenus intégrés de tiers : la carte Google Maps (Google) et, dans la galerie, le flux Instagram ou TikTok via des services comme SnapWidget ou LightWidget. Tant que tu ne les acceptes pas, ces contenus ne sont pas chargés. Ces prestataires peuvent recevoir ton adresse IP et des données de ton navigateur. Tu trouveras le détail dans la Politique de cookies.'],
                        ['h' => 'Transferts internationaux de données', 'p' => 'Certains des prestataires ci-dessus sont des sociétés établies aux États-Unis : Cloudflare (anti-bot), Google (carte) et les services du flux social (SnapWidget/LightWidget). Lorsqu\'ils sont actifs, l\'utilisation de ces services implique un transfert international de données vers les États-Unis, généralement couvert par le cadre de protection des données UE-États-Unis (Data Privacy Framework) ou par des clauses contractuelles types. Le mécanisme de transfert concret de chaque prestataire est [À COMPLÉTER : confirmer le Data Privacy Framework ou les clauses types de chaque prestataire]. La localisation des serveurs de notre hébergeur, et donc l\'existence d\'un transfert international via l\'hébergement, est [À COMPLÉTER : confirmer la localisation du serveur d\'hébergement].'],
                        ['h' => 'Pendant combien de temps nous conservons tes données', 'p' => 'Nous conservons les données de ton compte tant que ton compte reste actif et, ensuite, pendant les délais légaux qui nous l\'imposent ; en particulier, les données liées à tes commandes et factures sont conservées pendant les délais exigés par la législation fiscale et commerciale. Le délai fiscal concret de conservation des documents comptables est [À COMPLÉTER : confirmer le délai de conservation fiscale avec le comptable (à titre indicatif, entre 4 et 6 ans)]. Les commandes que tu laisses impayées expirent automatiquement à la fin de la réservation de place, libérant la capacité. Les registres prouvant ton consentement aux cookies sont conservés au maximum 24 mois. Ta session expire après une période d\'inactivité.'],
                        ['h' => 'Tes droits', 'p' => 'Tu peux exercer à tout moment tes droits d\'accès, de rectification, d\'effacement, d\'opposition, de limitation du traitement et de portabilité, et retirer tout consentement donné, sans que cela n\'affecte la licéité du traitement antérieur. Pour ta commodité, plusieurs de ces droits peuvent être exercés directement depuis « Mon compte » : télécharger une copie de toutes tes données dans un fichier lisible par machine (accès et portabilité) via l\'option d\'exportation, et rectifier ton nom, ton téléphone, ta langue ou ton email directement dans ton profil. Tu peux aussi supprimer ton compte depuis « Mon compte » : au lieu d\'effacer tes commandes, nous anonymisons ton compte (nous écrasons ton nom, ton email, ton téléphone et ton mot de passe, et supprimons tes consentements), en ne conservant que ce qui est strictement nécessaire au respect de nos obligations fiscales relatives aux factures. Pour exercer les autres droits, comme l\'opposition ou la limitation, ou si tu préfères demander l\'accès ou l\'effacement par écrit, écris-nous à :legal_email ; nous pourrons te demander de justifier ton identité.'],
                        ['h' => 'Communications commerciales et désinscription', 'p' => 'Nous ne t\'enverrons des communications commerciales que si tu y as expressément consenti lors de l\'inscription, jamais de manière précochée. Tu peux retirer ce consentement à tout moment en nous écrivant à :legal_email. Le mécanisme de désinscription directement depuis la communication elle-même ou depuis ton compte est [À COMPLÉTER : confirmer le mécanisme de désinscription marketing].'],
                        ['h' => 'Décisions automatisées et profilage', 'p' => 'Nous ne prenons pas de décisions automatisées produisant des effets juridiques à ton égard ou t\'affectant de manière significative, et nous n\'effectuons pas de profilage avec tes données.'],
                        ['h' => 'Mesures de sécurité', 'p' => 'Nous appliquons des mesures techniques et organisationnelles pour protéger tes données. Ton mot de passe est toujours conservé chiffré, et nous vérifions qu\'il ne figure pas dans des fuites de données connues avant de l\'accepter. Nous vérifions ton email via un lien à durée limitée et, si tu changes d\'email, nous ne remplaçons l\'actuel qu\'une fois le nouveau confirmé, en avertissant l\'ancien. Nous limitons les tentatives de connexion et d\'inscription pour décourager les attaques par force brute, et nous protégeons les formulaires publics contre les robots. Les sessions sont gérées par des cookies sécurisés et tu peux les fermer sur d\'autres appareils. Nous appliquons des en-têtes de sécurité et une politique de sécurité du contenu (CSP) sur le site. Dans nos journaux internes, nous minimisons les données : nous ne stockons ni mots de passe ni identifiants sensibles en clair, mais chiffrés ou anonymisés.'],
                        ['h' => 'Réclamation auprès de l\'autorité de contrôle', 'p' => 'Si tu estimes que le traitement de tes données n\'est pas conforme à la réglementation, tu as le droit d\'introduire une réclamation auprès de l\'Agence espagnole de protection des données (AEPD), située C/ Jorge Juan, 6, 28001 Madrid, et via son siège électronique www.aepd.es. Nous te serions toutefois reconnaissants de nous contacter au préalable à :legal_email afin d\'essayer de résoudre ta demande.'],
                    ],
                ],
            ],
            'condiciones' => [
                'title' => ['es' => 'Condiciones de uso y compra', 'en' => 'Terms of use and purchase', 'fr' => 'Conditions d\'utilisation et d\'achat'],
                'body' => [
                    'es' => [
                        ['h' => '1. Objeto y aceptación', 'p' => 'Estas Condiciones de uso y compra (en adelante, las «Condiciones») regulan el acceso y el uso de esta web, así como la compra en línea de entradas y la reserva de cumpleaños y eventos de :business_name. Al utilizar la web, registrar una cuenta o realizar un pedido, declaras haber leído y aceptado estas Condiciones. Si no estás de acuerdo con ellas, no debes usar la web ni comprar a través de ella. Podemos actualizar estas Condiciones para adaptarlas a cambios legales u operativos; te será de aplicación la versión vigente en el momento de tu compra, que aceptas marcando la casilla correspondiente al registrarte.'],
                        ['h' => '2. Titular y datos de contacto', 'p' => 'El titular de la web y responsable de la venta es :legal_name, con NIF :legal_nif y domicilio en :legal_address. Para cualquier consulta, reclamación o ejercicio de derechos relacionados con la web o tu pedido puedes escribirnos a :legal_email o llamarnos al :legal_phone.'],
                        ['h' => '3. Cuenta de usuario', 'p' => 'Para reservar y comprar necesitas crear una cuenta facilitando tu nombre, correo electrónico y teléfono, y elegir una contraseña. Te comprometes a aportar datos veraces y actualizados y a mantener la confidencialidad de tu contraseña; eres responsable de la actividad realizada desde tu cuenta. La cuenta se activa una vez verificado tu correo electrónico. Importante: el «registro del parque» y la exención de responsabilidad (waiver) NO se gestionan en esta web, sino en un sistema externo gestionado por el titular; cuando proceda, accederás a él desde el enlace que se te facilite. Esta web no recoge ni almacena el waiver.'],
                        ['h' => '4. Productos y servicios', 'p' => 'A través de la web puedes adquirir entradas asociadas a franjas horarias con aforo limitado, así como packs de cumpleaños y eventos, que pueden incluir complementos opcionales. Los packs de cumpleaños pueden requerir un número mínimo de invitados y, según se indique en la ficha del producto, el abono de una señal. La descripción, las condiciones y la disponibilidad de cada producto son las que figuran en su ficha en el momento de la compra. Procuramos que la información sea correcta, pero pueden producirse errores tipográficos o de disponibilidad; en tal caso te informaremos y, si fuera necesario, anularemos y reembolsaremos el pedido afectado.'],
                        ['h' => '5. Precios e impuestos', 'p' => 'Los precios se muestran en euros (€) e incluyen el IVA aplicable, calculado al tipo configurado en el sistema (:tax_rate). Algunos productos se anuncian con la indicación «desde X €», que corresponde al precio de partida según la franja, la tarifa o la fecha; el precio final aplicable es el que se te muestra en el detalle del pedido antes de pagar. Los precios vigentes son los publicados en el momento de formalizar la compra.'],
                        ['h' => '6. Proceso de compra y confirmación', 'p' => 'Para completar una compra debes seleccionar el producto y, en su caso, la franja horaria, revisar el detalle y el total de tu pedido y aceptar estas Condiciones antes de pagar. La plaza queda retenida durante un tiempo limitado mientras completas el pago; si no se completa dentro de ese plazo, el pedido caduca y la plaza se libera automáticamente. El contrato se entiende perfeccionado cuando se confirma el pago, momento en el que recibirás la confirmación y, cuando proceda, las entradas con su código de acceso.'],
                        ['h' => '7. Pago', 'p' => 'El pago se realiza a través de la pasarela bancaria segura Redsys. Los datos de tu tarjeta se introducen directamente en el entorno de Redsys y son tratados por dicho proveedor: nosotros no almacenamos el número de tu tarjeta. Solo conservamos la información necesaria para gestionar y conciliar el cobro (por ejemplo, importe, identificador y código de autorización de la operación). Si el cargo es rechazado o no se completa, el pedido no se considerará confirmado.'],
                        ['h' => '8. Aforo y franjas horarias', 'p' => 'Las entradas y reservas están sujetas a disponibilidad y al aforo de cada franja horaria. La compra de una entrada para una franja concreta no garantiza el acceso fuera de esa franja. El titular puede modificar horarios, cerrar fechas o ajustar el aforo por motivos operativos, de mantenimiento o de seguridad; si ello afecta a una reserva ya confirmada, se te ofrecerá una alternativa o el reembolso correspondiente.'],
                        ['h' => '9. Datos de los invitados en cumpleaños', 'p' => 'Para los packs de cumpleaños podemos solicitar, mediante un formulario, los datos de cada invitado (por ejemplo, nombre, alergias o intolerancias, menú especial y observaciones), con la única finalidad de organizar el evento y garantizar la seguridad alimentaria. Estos datos pueden referirse a menores y a información de salud (alergias/intolerancias). Debe ser el adulto contratante quien los aporte, garantizando que está legitimado para ello y, cuando corresponda, contando con el consentimiento de los responsables parentales. El conjunto exacto de datos solicitados es el que indique el formulario en cada caso.'],
                        ['h' => '10. Cancelaciones y reembolsos', 'p' => 'Las modificaciones y cancelaciones de un pedido las gestiona el personal del parque a petición tuya (a través de :legal_email o en el propio parque); no existe un autoservicio de cancelación desde tu cuenta. Cuando una modificación supone un importe adicional, este se abona en persona en el parque. Cuando una modificación o cancelación reduce el importe de un pedido ya pagado, se realiza un reembolso parcial automático al mismo medio de pago utilizado en la compra. Los plazos para cancelar o modificar, el tratamiento de las ausencias (no presentarse) y el carácter reembolsable o no de la señal de los packs de cumpleaños se rigen por la política de cancelación del parque: puedes cancelar o modificar tu reserva de cumpleaños hasta 3 días naturales antes de la fecha reservada y, en ese caso, la señal se reembolsa íntegramente; con menos de 3 días de antelación, o si no te presentas el día reservado (no-show), la señal no es reembolsable.'],
                        ['h' => '11. Obligaciones y conducta del usuario', 'p' => 'Te comprometes a usar la web y los servicios de forma lícita y conforme a estas Condiciones, a no facilitar datos falsos ni utilizar las entradas de forma fraudulenta. Dentro del parque debes respetar en todo momento las normas de uso y de seguridad y las indicaciones del personal. Puedes consultar las Normas del parque en la web; su incumplimiento puede conllevar la denegación o la retirada del acceso, sin derecho a reembolso.'],
                        ['h' => '12. Responsabilidad y disponibilidad del servicio', 'p' => 'Procuramos que la web esté disponible y que su información sea correcta y esté actualizada, pero no podemos garantizar la ausencia de interrupciones o errores. Podremos suspender temporalmente el acceso por mantenimiento o por causas técnicas. No respondemos de los daños derivados de un uso indebido de la web o de los servicios, ni de causas de fuerza mayor ajenas a nuestro control. Nada en estas Condiciones limita la responsabilidad que legalmente no pueda excluirse.'],
                        ['h' => '13. Propiedad intelectual', 'p' => 'Los contenidos de la web (textos, imágenes, logotipos, marcas y diseño) pertenecen a su titular o a sus licenciantes y están protegidos por la normativa de propiedad intelectual e industrial. No se permite su reproducción, distribución ni uso sin autorización previa.'],
                        ['h' => '14. Protección de datos', 'p' => 'El tratamiento de tus datos personales se rige por nuestra Política de privacidad, que puedes consultar en la web y donde se detallan las finalidades, las bases jurídicas, los plazos de conservación y cómo ejercer tus derechos. Al aceptar estas Condiciones declaras haber sido informado de dicha Política.'],
                        ['h' => '15. Legislación aplicable y resolución de conflictos', 'p' => 'Estas Condiciones se rigen por la legislación española. Si actúas como consumidor, podrás reclamar ante los juzgados y tribunales de tu lugar de domicilio. Para cualquier otro supuesto, las partes se someten a los juzgados y tribunales de :jurisdiction. Como consumidor, también puedes acudir a la plataforma europea de resolución de litigios en línea de la Comisión Europea, disponible en https://ec.europa.eu/consumers/odr.'],
                    ],
                    'en' => [
                        ['h' => '1. Purpose and acceptance', 'p' => 'These Terms of use and purchase (the "Terms") govern access to and use of this website, as well as the online purchase of tickets and the booking of birthday parties and events at :business_name. By using the website, registering an account or placing an order, you declare that you have read and accepted these Terms. If you do not agree with them, you must not use the website or buy through it. We may update these Terms to reflect legal or operational changes; the version applicable to you is the one in force at the time of your purchase, which you accept by ticking the relevant box when you register.'],
                        ['h' => '2. Owner and contact details', 'p' => 'The owner of the website and seller is :legal_name, tax ID :legal_nif, registered at :legal_address. For any query, complaint or to exercise rights relating to the website or your order, you can write to us at :legal_email or call us on :legal_phone.'],
                        ['h' => '3. User account', 'p' => 'To book and buy you need to create an account by providing your name, email and phone number, and choosing a password. You agree to provide accurate, up-to-date information and to keep your password confidential; you are responsible for activity carried out from your account. The account is activated once your email has been verified. Important: the "park registration" and the liability waiver are NOT handled on this website, but on an external system managed by the owner; where applicable, you will access it via the link provided to you. This website does not collect or store the waiver.'],
                        ['h' => '4. Products and services', 'p' => 'Through the website you can buy tickets tied to time slots with limited capacity, as well as birthday and event packs, which may include optional add-ons. Birthday packs may require a minimum number of guests and, where indicated on the product page, the payment of a deposit. The description, conditions and availability of each product are those shown on its page at the time of purchase. We aim to keep the information accurate, but typographical or availability errors may occur; in that case we will inform you and, if necessary, cancel and refund the affected order.'],
                        ['h' => '5. Prices and taxes', 'p' => 'Prices are shown in euros (€) and include the applicable VAT, calculated at the rate configured in the system (:tax_rate). Some products are advertised "from X €", which is the starting price depending on the slot, rate or date; the final price applicable to you is the one shown in your order details before payment. The prices in force are those published at the time the purchase is made.'],
                        ['h' => '6. Purchase process and confirmation', 'p' => 'To complete a purchase you must select the product and, where applicable, the time slot, review your order details and total, and accept these Terms before paying. Your place is held for a limited time while you complete payment; if payment is not completed within that period, the order expires and the place is automatically released. The contract is formed when payment is confirmed, at which point you will receive your confirmation and, where applicable, your tickets with their access code.'],
                        ['h' => '7. Payment', 'p' => 'Payment is made through the secure bank gateway Redsys. Your card details are entered directly in the Redsys environment and processed by that provider: we do not store your card number. We only keep the information needed to manage and reconcile the charge (for example, amount, transaction identifier and authorisation code). If the charge is declined or not completed, the order will not be deemed confirmed.'],
                        ['h' => '8. Capacity and time slots', 'p' => 'Tickets and bookings are subject to availability and to the capacity of each time slot. Buying a ticket for a particular slot does not grant access outside that slot. The owner may change opening hours, close dates or adjust capacity for operational, maintenance or safety reasons; if this affects a confirmed booking, you will be offered an alternative or the corresponding refund.'],
                        ['h' => '9. Guest data for birthday parties', 'p' => 'For birthday packs we may ask, through a form, for the details of each guest (for example, name, allergies or intolerances, special menu and notes), for the sole purpose of organising the event and ensuring food safety. This data may relate to minors and to health information (allergies/intolerances). It must be the contracting adult who provides it, ensuring they are entitled to do so and, where applicable, having the consent of the parents or guardians. The exact set of data requested is the one indicated by the form in each case.'],
                        ['h' => '10. Cancellations and refunds', 'p' => 'Changes and cancellations to an order are handled by park staff at your request (via :legal_email or at the park itself); there is no self-service cancellation from your account. Where a change involves an additional amount, this is paid in person at the park. Where a change or cancellation reduces the amount of an order that has already been paid, an automatic partial refund is made to the same means of payment used for the purchase. The deadlines to cancel or change, the treatment of no-shows and whether the birthday pack deposit is refundable are governed by the park\'s cancellation policy: you may cancel or change your birthday booking up to 3 calendar days before the booked date, in which case the deposit is refunded in full; with less than 3 days\' notice, or if you do not show up on the booked date (no-show), the deposit is non-refundable.'],
                        ['h' => '11. User obligations and conduct', 'p' => 'You agree to use the website and services lawfully and in accordance with these Terms, not to provide false data and not to use tickets fraudulently. Within the park you must at all times follow the rules of use and safety and the instructions of staff. You can consult the Park rules on the website; breaching them may lead to access being refused or withdrawn, with no right to a refund.'],
                        ['h' => '12. Liability and service availability', 'p' => 'We aim to keep the website available and its information accurate and up to date, but we cannot guarantee that it will be free of interruptions or errors. We may temporarily suspend access for maintenance or technical reasons. We are not liable for damages arising from improper use of the website or services, nor for force majeure events beyond our control. Nothing in these Terms limits liability that cannot legally be excluded.'],
                        ['h' => '13. Intellectual property', 'p' => 'The website content (texts, images, logos, trademarks and design) belongs to its owner or its licensors and is protected by intellectual and industrial property law. Its reproduction, distribution or use without prior authorisation is not permitted.'],
                        ['h' => '14. Data protection', 'p' => 'The processing of your personal data is governed by our Privacy policy, which you can consult on the website and which sets out the purposes, legal bases, retention periods and how to exercise your rights. By accepting these Terms, you declare that you have been informed of that Policy.'],
                        ['h' => '15. Applicable law and dispute resolution', 'p' => 'These Terms are governed by Spanish law. If you act as a consumer, you may bring a claim before the courts of your place of residence. In any other case, the parties submit to the courts of :jurisdiction. As a consumer, you may also use the European Commission\'s online dispute resolution platform, available at https://ec.europa.eu/consumers/odr.'],
                    ],
                    'fr' => [
                        ['h' => '1. Objet et acceptation', 'p' => 'Ces Conditions d\'utilisation et d\'achat (les « Conditions ») régissent l\'accès et l\'utilisation de ce site, ainsi que l\'achat en ligne de billets et la réservation d\'anniversaires et d\'événements chez :business_name. En utilisant le site, en créant un compte ou en passant une commande, tu déclares avoir lu et accepté ces Conditions. Si tu n\'es pas d\'accord, tu ne dois ni utiliser le site ni y acheter. Nous pouvons mettre à jour ces Conditions pour les adapter à des changements légaux ou opérationnels ; la version qui s\'applique à toi est celle en vigueur au moment de ton achat, que tu acceptes en cochant la case correspondante lors de l\'inscription.'],
                        ['h' => '2. Éditeur et coordonnées', 'p' => 'L\'éditeur du site et vendeur est :legal_name, NIF :legal_nif, domicilié à :legal_address. Pour toute question, réclamation ou exercice de tes droits liés au site ou à ta commande, tu peux nous écrire à :legal_email ou nous appeler au :legal_phone.'],
                        ['h' => '3. Compte utilisateur', 'p' => 'Pour réserver et acheter, tu dois créer un compte en fournissant ton nom, ton email et ton téléphone, et en choisissant un mot de passe. Tu t\'engages à fournir des données exactes et à jour et à garder ton mot de passe confidentiel ; tu es responsable de l\'activité réalisée depuis ton compte. Le compte est activé une fois ton email vérifié. Important : l\'« inscription du parc » et la décharge de responsabilité (waiver) NE sont PAS gérées sur ce site, mais sur un système externe géré par l\'éditeur ; le cas échéant, tu y accéderas via le lien qui te sera fourni. Ce site ne collecte ni ne conserve la décharge.'],
                        ['h' => '4. Produits et services', 'p' => 'Sur le site, tu peux acheter des billets associés à des créneaux horaires à capacité limitée, ainsi que des packs d\'anniversaire et d\'événements, qui peuvent inclure des compléments optionnels. Les packs d\'anniversaire peuvent exiger un nombre minimum d\'invités et, selon ce qu\'indique la fiche du produit, le versement d\'un acompte. La description, les conditions et la disponibilité de chaque produit sont celles figurant sur sa fiche au moment de l\'achat. Nous veillons à l\'exactitude de l\'information, mais des erreurs typographiques ou de disponibilité peuvent survenir ; le cas échéant, nous t\'en informerons et, si nécessaire, annulerons et rembourserons la commande concernée.'],
                        ['h' => '5. Prix et taxes', 'p' => 'Les prix sont affichés en euros (€) et incluent la TVA applicable, calculée au taux configuré dans le système (:tax_rate). Certains produits sont annoncés « à partir de X € », ce qui correspond au prix de départ selon le créneau, le tarif ou la date ; le prix final qui t\'est applicable est celui affiché dans le détail de ta commande avant le paiement. Les prix en vigueur sont ceux publiés au moment de finaliser l\'achat.'],
                        ['h' => '6. Processus d\'achat et confirmation', 'p' => 'Pour finaliser un achat, tu dois sélectionner le produit et, le cas échéant, le créneau horaire, vérifier le détail et le total de ta commande et accepter ces Conditions avant de payer. Ta place est réservée pendant un temps limité le temps de finaliser le paiement ; si celui-ci n\'est pas effectué dans ce délai, la commande expire et la place est automatiquement libérée. Le contrat est conclu lorsque le paiement est confirmé ; tu reçois alors ta confirmation et, le cas échéant, tes billets avec leur code d\'accès.'],
                        ['h' => '7. Paiement', 'p' => 'Le paiement s\'effectue via la passerelle bancaire sécurisée Redsys. Les données de ta carte sont saisies directement dans l\'environnement de Redsys et traitées par ce prestataire : nous ne stockons pas le numéro de ta carte. Nous ne conservons que les informations nécessaires pour gérer et rapprocher le paiement (par exemple, montant, identifiant et code d\'autorisation de l\'opération). Si le débit est refusé ou non finalisé, la commande ne sera pas considérée comme confirmée.'],
                        ['h' => '8. Capacité et créneaux horaires', 'p' => 'Les billets et réservations sont soumis à disponibilité et à la capacité de chaque créneau horaire. L\'achat d\'un billet pour un créneau précis ne garantit pas l\'accès en dehors de ce créneau. L\'éditeur peut modifier les horaires, fermer des dates ou ajuster la capacité pour des raisons opérationnelles, de maintenance ou de sécurité ; si cela affecte une réservation confirmée, une alternative ou le remboursement correspondant te sera proposé.'],
                        ['h' => '9. Données des invités pour les anniversaires', 'p' => 'Pour les packs d\'anniversaire, nous pouvons demander, via un formulaire, les données de chaque invité (par exemple, nom, allergies ou intolérances, menu spécial et observations), à la seule fin d\'organiser l\'événement et de garantir la sécurité alimentaire. Ces données peuvent concerner des mineurs et des informations de santé (allergies/intolérances). C\'est à l\'adulte contractant de les fournir, en garantissant qu\'il est habilité à le faire et, le cas échéant, en disposant du consentement des responsables parentaux. L\'ensemble exact des données demandées est celui indiqué par le formulaire dans chaque cas.'],
                        ['h' => '10. Annulations et remboursements', 'p' => 'Les modifications et annulations d\'une commande sont gérées par le personnel du parc à ta demande (via :legal_email ou au parc lui-même) ; il n\'existe pas d\'annulation en libre-service depuis ton compte. Lorsqu\'une modification implique un montant supplémentaire, celui-ci est réglé en personne au parc. Lorsqu\'une modification ou une annulation réduit le montant d\'une commande déjà payée, un remboursement partiel automatique est effectué sur le même moyen de paiement utilisé lors de l\'achat. Les délais pour annuler ou modifier, le traitement des absences (no-show) et le caractère remboursable ou non de l\'acompte des packs d\'anniversaire sont régis par la politique d\'annulation du parc : tu peux annuler ou modifier ta réservation d\'anniversaire jusqu\'à 3 jours calendaires avant la date réservée, auquel cas l\'acompte est intégralement remboursé ; avec moins de 3 jours de préavis, ou si tu ne te présentes pas à la date réservée (no-show), l\'acompte n\'est pas remboursable.'],
                        ['h' => '11. Obligations et conduite de l\'utilisateur', 'p' => 'Tu t\'engages à utiliser le site et les services de façon licite et conforme à ces Conditions, à ne pas fournir de données fausses et à ne pas utiliser les billets de manière frauduleuse. Dans le parc, tu dois respecter à tout moment les règles d\'utilisation et de sécurité et les consignes du personnel. Tu peux consulter les Règles du parc sur le site ; leur non-respect peut entraîner le refus ou le retrait de l\'accès, sans droit à remboursement.'],
                        ['h' => '12. Responsabilité et disponibilité du service', 'p' => 'Nous veillons à la disponibilité du site et à l\'exactitude et l\'actualité de son information, mais nous ne pouvons garantir l\'absence d\'interruptions ou d\'erreurs. Nous pouvons suspendre temporairement l\'accès pour maintenance ou pour des raisons techniques. Nous ne répondons pas des dommages résultant d\'un usage abusif du site ou des services, ni des cas de force majeure échappant à notre contrôle. Rien dans ces Conditions ne limite la responsabilité qui ne peut légalement être exclue.'],
                        ['h' => '13. Propriété intellectuelle', 'p' => 'Les contenus du site (textes, images, logos, marques et design) appartiennent à son éditeur ou à ses concédants et sont protégés par le droit de la propriété intellectuelle et industrielle. Leur reproduction, distribution ou utilisation sans autorisation préalable n\'est pas permise.'],
                        ['h' => '14. Protection des données', 'p' => 'Le traitement de tes données personnelles est régi par notre Politique de confidentialité, que tu peux consulter sur le site et qui détaille les finalités, les bases juridiques, les durées de conservation et la façon d\'exercer tes droits. En acceptant ces Conditions, tu déclares avoir été informé de cette Politique.'],
                        ['h' => '15. Droit applicable et résolution des litiges', 'p' => 'Ces Conditions sont régies par le droit espagnol. Si tu agis en tant que consommateur, tu pourras saisir les tribunaux de ton lieu de domicile. Dans tout autre cas, les parties se soumettent aux tribunaux de :jurisdiction. En tant que consommateur, tu peux aussi recourir à la plateforme européenne de règlement en ligne des litiges de la Commission européenne, disponible sur https://ec.europa.eu/consumers/odr.'],
                    ],
                ],
            ],
            'aviso-legal' => [
                'title' => ['es' => 'Aviso legal', 'en' => 'Legal notice', 'fr' => 'Mentions légales'],
                'body' => [
                    'es' => [
                        ['h' => 'Datos identificativos del titular', 'p' => 'En cumplimiento del artículo 10 de la Ley 34/2002 de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), te informamos de que el titular de este sitio web es :legal_name, con NIF :legal_nif y domicilio en :legal_address. Puedes contactar con nosotros en :legal_email o por teléfono en el :legal_phone.'],
                        ['h' => 'Objeto y ámbito', 'p' => 'Este aviso legal regula el acceso, la navegación y el uso del sitio web :site_domain, a través del cual ofrecemos información sobre el parque :business_name y permitimos registrarte, comprar entradas y reservar cumpleaños y eventos. El acceso al sitio implica que aceptas estas condiciones; si no estás de acuerdo, te pedimos que no lo utilices.'],
                        ['h' => 'Condiciones de uso del sitio', 'p' => 'Te comprometes a usar el sitio de forma lícita, conforme a la ley, a la buena fe y a este aviso, y a no realizar actividades que dañen, sobrecarguen o impidan el funcionamiento normal de la web. Los datos que nos facilites (al registrarte, comprar o contactarnos) deben ser veraces, exactos y actualizados, y eres responsable de la información que aportes. Para crear una cuenta y comprar necesitas verificar tu correo electrónico.'],
                        ['h' => 'Propiedad intelectual e industrial', 'p' => 'Los contenidos del sitio (textos, imágenes, diseño, código y demás elementos), así como la marca y los signos distintivos de :business_name, pertenecen a :legal_name o a sus licenciantes y están protegidos por la normativa de propiedad intelectual e industrial. No se permite su reproducción, distribución, transformación ni cualquier otro uso sin autorización expresa, salvo el uso personal necesario para navegar y contratar nuestros servicios.'],
                        ['h' => 'Responsabilidad', 'p' => 'Procuramos que la información del sitio sea correcta y esté actualizada, pero no podemos garantizar la ausencia de errores ni la disponibilidad ininterrumpida del servicio; podemos suspenderlo temporalmente por mantenimiento o causas técnicas. El sitio puede mostrar contenidos de terceros mediante incrustaciones (por ejemplo, el mapa de Google Maps y el feed social de Instagram o TikTok), que solo se cargan si aceptas las cookies correspondientes; no controlamos esos servicios externos y no nos hacemos responsables de su contenido, disponibilidad ni de sus propias políticas. No respondemos del uso indebido que terceros hagan del sitio ni de los daños derivados de un uso contrario a este aviso.'],
                        ['h' => 'Protección de datos y cookies', 'p' => 'El tratamiento de tus datos personales se rige por nuestra Política de privacidad, y el uso de cookies y de contenidos de terceros por nuestra Política de cookies, ambas accesibles desde el pie de página. Puedes aceptar, configurar por categorías o retirar tu consentimiento de cookies en cualquier momento desde «Configuración de cookies». Te recomendamos consultarlas para conocer qué datos tratamos, con qué finalidad y cómo ejercer tus derechos.'],
                        ['h' => 'Legislación aplicable y jurisdicción', 'p' => 'Este aviso legal se rige por la legislación española. Para la resolución de cualquier controversia se estará a lo que disponga la normativa aplicable; si eres consumidor, podrás acudir a los tribunales de tu lugar de domicilio conforme a la normativa de consumo. Para cualquier otro supuesto, las partes se someten a los juzgados y tribunales de :jurisdiction.'],
                        ['h' => 'Modificaciones del aviso', 'p' => 'Podemos modificar este aviso legal para adaptarlo a cambios normativos o a la evolución del sitio. La versión publicada en cada momento es la aplicable, por lo que te recomendamos revisarlo periódicamente.'],
                    ],
                    'en' => [
                        ['h' => 'Owner identification details', 'p' => 'In compliance with article 10 of Spanish Law 34/2002 on Information Society Services and Electronic Commerce (LSSI-CE), we inform you that the owner of this website is :legal_name, tax ID :legal_nif, registered at :legal_address. You can contact us at :legal_email or by phone on :legal_phone.'],
                        ['h' => 'Purpose and scope', 'p' => 'This legal notice governs access to, browsing of and use of the website :site_domain, through which we provide information about :business_name park and allow you to register, buy tickets and book birthdays and events. Accessing the site means you accept these terms; if you do not agree, please do not use it.'],
                        ['h' => 'Conditions of use', 'p' => 'You agree to use the site lawfully, in accordance with the law, good faith and this notice, and not to carry out activities that damage, overload or disrupt the normal operation of the website. The data you provide (when registering, buying or contacting us) must be truthful, accurate and up to date, and you are responsible for the information you supply. To create an account and buy, you need to verify your email address.'],
                        ['h' => 'Intellectual and industrial property', 'p' => 'The site content (text, images, design, code and other elements), as well as the :business_name brand and distinctive signs, belong to :legal_name or its licensors and are protected by intellectual and industrial property law. Their reproduction, distribution, transformation or any other use is not permitted without express authorisation, except for the personal use needed to browse and purchase our services.'],
                        ['h' => 'Liability', 'p' => 'We aim to keep the information on the site accurate and up to date, but cannot guarantee that it is free of errors or that the service will be available without interruption; we may suspend it temporarily for maintenance or technical reasons. The site may display third-party content via embeds (for example, the Google Maps map and the Instagram or TikTok social feed), which only load if you accept the relevant cookies; we do not control those external services and are not responsible for their content, availability or their own policies. We are not liable for any misuse of the site by third parties or for damages arising from use contrary to this notice.'],
                        ['h' => 'Data protection and cookies', 'p' => 'The processing of your personal data is governed by our Privacy policy, and the use of cookies and third-party content by our Cookie policy, both accessible from the footer. You can accept, configure by category or withdraw your cookie consent at any time from "Cookie settings". We recommend reviewing them to learn what data we process, for what purpose and how to exercise your rights.'],
                        ['h' => 'Applicable law and jurisdiction', 'p' => 'This legal notice is governed by Spanish law. Any dispute will be settled in accordance with the applicable rules; if you are a consumer, you may bring the matter before the courts of your place of residence under consumer protection law. In any other case, the parties submit to the courts of :jurisdiction.'],
                        ['h' => 'Changes to this notice', 'p' => 'We may amend this legal notice to adapt it to regulatory changes or to the evolution of the site. The version published at any given time is the one that applies, so we recommend reviewing it periodically.'],
                    ],
                    'fr' => [
                        ['h' => 'Données d\'identification de l\'éditeur', 'p' => 'Conformément à l\'article 10 de la loi espagnole 34/2002 sur les services de la société de l\'information et le commerce électronique (LSSI-CE), nous t\'informons que l\'éditeur de ce site est :legal_name, NIF :legal_nif, domicilié à :legal_address. Tu peux nous contacter à :legal_email ou par téléphone au :legal_phone.'],
                        ['h' => 'Objet et champ d\'application', 'p' => 'Cette mention légale régit l\'accès, la navigation et l\'utilisation du site web :site_domain, à travers lequel nous présentons le parc :business_name et te permettons de t\'inscrire, d\'acheter des billets et de réserver des anniversaires et des événements. L\'accès au site implique que tu acceptes ces conditions ; si tu n\'es pas d\'accord, nous te demandons de ne pas l\'utiliser.'],
                        ['h' => 'Conditions d\'utilisation du site', 'p' => 'Tu t\'engages à utiliser le site de manière licite, dans le respect de la loi, de la bonne foi et de cette mention, et à ne pas mener d\'activités susceptibles d\'endommager, de surcharger ou d\'empêcher le fonctionnement normal du site. Les données que tu fournis (lors de l\'inscription, de l\'achat ou d\'une prise de contact) doivent être véridiques, exactes et à jour, et tu es responsable des informations que tu communiques. Pour créer un compte et acheter, tu dois vérifier ton adresse e-mail.'],
                        ['h' => 'Propriété intellectuelle et industrielle', 'p' => 'Les contenus du site (textes, images, design, code et autres éléments), ainsi que la marque et les signes distinctifs de :business_name, appartiennent à :legal_name ou à ses concédants et sont protégés par le droit de la propriété intellectuelle et industrielle. Leur reproduction, distribution, transformation ou tout autre usage n\'est pas autorisé sans accord exprès, hormis l\'usage personnel nécessaire pour naviguer et souscrire à nos services.'],
                        ['h' => 'Responsabilité', 'p' => 'Nous veillons à ce que les informations du site soient correctes et à jour, mais nous ne pouvons garantir l\'absence d\'erreurs ni la disponibilité ininterrompue du service ; nous pouvons le suspendre temporairement pour maintenance ou raisons techniques. Le site peut afficher des contenus de tiers via des intégrations (par exemple la carte Google Maps et le flux social Instagram ou TikTok), qui ne se chargent que si tu acceptes les cookies correspondants ; nous ne contrôlons pas ces services externes et ne sommes pas responsables de leur contenu, de leur disponibilité ni de leurs propres politiques. Nous ne répondons pas de l\'usage abusif du site par des tiers ni des dommages résultant d\'un usage contraire à cette mention.'],
                        ['h' => 'Protection des données et cookies', 'p' => 'Le traitement de tes données personnelles est régi par notre Politique de confidentialité, et l\'utilisation des cookies et des contenus de tiers par notre Politique de cookies, toutes deux accessibles depuis le pied de page. Tu peux accepter, configurer par catégorie ou retirer ton consentement aux cookies à tout moment depuis « Paramètres des cookies ». Nous te recommandons de les consulter pour savoir quelles données nous traitons, dans quel but et comment exercer tes droits.'],
                        ['h' => 'Droit applicable et juridiction', 'p' => 'Cette mention légale est régie par le droit espagnol. Tout litige sera réglé selon la réglementation applicable ; si tu es consommateur, tu pourras saisir les tribunaux de ton lieu de domicile conformément au droit de la consommation. Dans tout autre cas, les parties se soumettent aux tribunaux de :jurisdiction.'],
                        ['h' => 'Modifications de la mention', 'p' => 'Nous pouvons modifier cette mention légale pour l\'adapter aux évolutions réglementaires ou à celles du site. La version publiée à chaque instant est celle qui s\'applique ; nous te recommandons donc de la consulter régulièrement.'],
                    ],
                ],
            ],
        ];
    }
}
